# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics_logs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12metrics_logs.proto\x12\ttelemetry\"$\n\x05Label\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"S\n\x08LogEntry\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\x12 \n\x06labels\x18\x03 \x03(\x0b\x32\x10.telemetry.Label\"\xcb\x01\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12 \n\x06labels\x18\x04 \x03(\x0b\x32\x10.telemetry.Label\x12*\n\x04type\x18\x05 \x01(\x0e\x32\x1c.telemetry.Metric.MetricType\"@\n\nMetricType\x12\x0b\n\x07\x43OUNTER\x10\x00\x12\t\n\x05GAUGE\x10\x01\x12\r\n\tHISTOGRAM\x10\x02\x12\x0b\n\x07SUMMARY\x10\x03\"~\n\x10TelemetryMessage\x12!\n\x04logs\x18\x01 \x03(\x0b\x32\x13.telemetry.LogEntry\x12\"\n\x07metrics\x18\x02 \x03(\x0b\x32\x11.telemetry.Metric\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x13\n\x0binstance_id\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_logs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LABEL._serialized_start=33
  _LABEL._serialized_end=69
  _LOGENTRY._serialized_start=71
  _LOGENTRY._serialized_end=154
  _METRIC._serialized_start=157
  _METRIC._serialized_end=360
  _METRIC_METRICTYPE._serialized_start=296
  _METRIC_METRICTYPE._serialized_end=360
  _TELEMETRYMESSAGE._serialized_start=362
  _TELEMETRYMESSAGE._serialized_end=488
# @@protoc_insertion_point(module_scope)
